config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('social.accounts.urls', namespace='accounts')),
    path('', include('social.pages.urls', namespace='pages')),
    path('blog/', include('social.blog.urls', namespace='blog')),
    path('notifications/', include('social.notifications.urls', namespace='notifications')),
    path('chat/', include('social.chat.urls', namespace='chat')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/chat/urls.py
from django.urls import path

from . import views


app_name = 'chat'

urlpatterns = [
    path('', views.room_list_view, name='list'),
    path('<int:friend_id>/', views.room_choice_view, name='choice'),
    path('room/<int:room_id>-<int:friend_id>/', views.room_view, name='room'),
]

social/chat/models.py
from django.db import models
from django.conf import settings


class Room(models.Model):
    room_id = models.AutoField(primary_key=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='author_room'
    )
    friend = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='friend_room'
    )
    datetime_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Room'
        verbose_name_plural = 'Rooms'

    def __str__(self):
        return f'{self.room_id} / {self.author} / {self.friend}'
    

class Chat(models.Model):
    room_id = models.ForeignKey(
        Room,
        on_delete=models.CASCADE,
        related_name='chats'
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='author_message'
    )
    text = models.TextField(default='')
    datetime_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Chat'
        verbose_name_plural = 'Chats'

    def __str__(self):
        return f'{self.pk} / {self.datetime_created}'

social/chat/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import get_user_model
from django.db.models import Q
from django.utils.safestring import mark_safe
import json

from social.chat.models import Chat, Room


User = get_user_model()


def room_list_view(request):
    user = request.user
    rooms = Room.objects.filter(
        Q(author=user) | Q(friend=user)
    ).order_by('-datetime_created')

    return render(request, 'chat/list.html', {'rooms': rooms})


def room_choice_view(request, friend_id):
    user = request.user

    try:
        friend = User.objects.get(pk=friend_id)
    except User.DoesNotExist:
        return redirect('chat:list')
        
    room = Room.objects.filter(
        Q(author=user, friend=friend) | Q(author=friend, friend=user)
    ).first()

    if not room:
        room = Room.objects.create(author=user, friend=friend)
        return redirect('chat:room', room.room_id, friend_id)
    
    return redirect('chat:room', room.room_id, friend_id)


def room_view(request, room_id, friend_id):

    try:
        Room.objects.filter(room_id=room_id)
        friend = User.objects.get(pk=friend_id)
    except Room.DoesNotExist:
        return redirect('chat:list')
    except User.DoesNotExist:
        return redirect('chat:list')
    
    chats = Chat.objects.filter(
        room_id=room_id
    ).order_by('datetime_created')

    return render(request, 'chat/room.html', {
        'chats': chats, 
        'friend': friend,
        'room_id_json': mark_safe(json.dumps(room_id))
    })

social/chat/templates/chat/list.html
{% extends '_base.html' %}

{% block title %}
    Room List
{% endblock title %}

{% block content %}
    {% for room in rooms %}
        {% if room.friend == user %}
            <p><a href="{% url 'chat:choice' room.author.id %}">{{ room.author.profile }}</a></p>
            <p>{{ room.author.pk }}</p>
        {% else %}
            <p><a href="{% url 'chat:choice' room.friend.id %}">{{ room.friend.profile }}</a></p>
            <p>{{ room.friend.pk }}</p>
        {% endif %}
    {% endfor %}
{% endblock content %}

social/chat/templates/chat/room.html
{% extends '_base.html' %}

{% block title %}
    Room
{% endblock title %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="mb-sm-3 col-md-12">
                <div class="card">
                    <div class="card-header">
                        {{ friend }} Room
                    </div>
                    <div class="card-body">
                        <div id="messages-list" class="border px-2 py-2 mb-2" style="height: 200px; overflow-y: scroll">
                            {% for chat in chats %}
                            <div class="media">
                                <div class="media-body">
                                    {% if chat.author == user %}
                                        <h6 class="my-0 text-success"><strong>You</strong></h6>
                                    {% else %}
                                        <h6 class="my-0"><strong>{{ chat.author }}</strong></h6>
                                    {% endif %}
                                        <p>{{ chat.text }}</p>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="form-inline">
                            <div class="form-group mr-2 mb-2">
                            <input type="text" class="form-control" id="msg-input" placeholder="Enter your Message Text">
                            </div>
                            <button id="msg-submit" type="submit" class="btn btn-primary mb-2">Send</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- {{ room_id|json_script:"room-id" }} -->

{% endblock content %}

{% block scripts %}

<script>

    var room_id = {{ room_id_json }};
    var msgdiv = $('#messages-list');

    window.onload = function(e){
        msgdiv.scrollTop(msgdiv.prop('scrollHeight'));
    }

    var socket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + room_id + '/'
    );

    socket.onmessage = function(e) {
        var message = JSON.parse(e.data);
        msgdiv.append(`
            <div class="media">
                <div class="media-body">
                    <h6 class="my-0"><strong>USERNAME</strong></h6>
                    <p>MESSAGE</p>
                </div>
            </div>
        `.replace('USERNAME', message['sender']).replace('MESSAGE', message['text']));
    };

    socket.onclose = function(e) {
        console.error('Socket closed unexpectedly.')
    };

    socket.onopen = function(e) {
        console.log('Successfully connected to the WebSocket.');
    };

    document.querySelector('#msg-input').focus();
    document.querySelector('#msg-input').onkeyup = function(e) {
        if (e.keyCode == 13) {
            document.querySelector('#msg-submit').click();
        }
    };

    document.querySelector('#msg-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#msg-input');
        var message = messageInputDom.value;

        msgdiv.append(`
            <div class="media">
                <div class="media-body">
                    <h6 class="my-0 text-success"><strong>You</strong></h6>
                    <p>MESSAGE</p>
                </div>
            </div>
        `.replace('MESSAGE', message));

        msgdiv.scrollTop(msgdiv.prop('scrollHeight'));

        socket.send(JSON.stringify({'text': message}));

        messageInputDom.value = '';
    };






//     var room_id = JSON.parse(document.getElementById('room-id').textContent);
//     var msgdiv = $('#messages-list');

//     window.onload = function(e){
//         msgdiv.scrollTop(msgdiv.prop("scrollHeight"));
//     }

//     var socket = new WebSocket(
//         'ws://' + window.location.host +
//         '/ws/chat/' + room_id + '/');
        
//     socket.onmessage = function(e) {
//         var message = JSON.parse(e.data);

//         switch (message['type']) {
//             case 'msg':
//                 msgdiv.append(`
//                     <div class="media">
//                         <div class="media-body">
//                             <h6 class="my-0"><strong>USERNAME</strong></h6>
//                             <p>MESSAGE</p>
//                         </div>
//                     </div>
//                 `.replace('USERNAME', message['sender']).replace('MESSAGE', message['text']));
//                 break;
//             default:
//                 break;
//         }
//         msgdiv.scrollTop(msgdiv.prop("scrollHeight"));
//     };

//     socket.onclose = function(e) {
//         console.error('Socket closed unexpectedly');
//     };

//     document.querySelector('#msg-input').focus();
//     document.querySelector('#msg-input').onkeyup = function(e) {
//         if (e.keyCode === 13) {
//             document.querySelector('#msg-submit').click();
//         }
//     };

//     document.querySelector('#msg-submit').onclick = function(e) {
//         var messageInputDom = document.querySelector('#msg-input');
//         var message = messageInputDom.value;

//         msgdiv.append(`
//             <div class="media">
//                 <div class="media-body">
//                     <h6 class="my-0 text-success"><strong>You</strong></h6>
//                     <p>MESSAGE</p>
//                 </div>
//             </div>
//         `.replace('MESSAGE', message));

//         msgdiv.scrollTop(msgdiv.prop("scrollHeight"));

//         socket.send(JSON.stringify({'text': message}));

//         messageInputDom.value = '';
//     };





</script>

{% endblock scripts %}