config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('social.accounts.urls', namespace='accounts')),
    path('', include('social.pages.urls', namespace='pages')),
    path('blog/', include('social.blog.urls', namespace='blog')),
    path('notifications/', include('social.notifications.urls', namespace='notifications')),
    path('chat/', include('social.chat.urls', namespace='chat')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/blog/urls.py
from django.urls import path, re_path

from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('liked/', 
        views.UserPostLikeView.as_view(), name='post_user_like_list'
    ),
    path('saved/', 
        views.WishListView.as_view(), name='post_wish_list'
    ),
    path('save/<int:post_id>/', 
        views.post_favorite, name='post_save'
    ),
    path('search/', 
         views.SearchListView.as_view(), name='post_search_list'
    ),
    path('create/', 
        views.PostCreateView.as_view(), name='post_create'
    ),
    path('user/<str:username>/',
        views.UserPostListView.as_view(), name='user_post_list'
    ),
    path('like/post/<int:post_id>/',
        views.post_like, name='post_like'
    ),
    path('like/comment/<int:comment_id>/',
        views.comment_like, name='comment_like'
    ),
    re_path(r'(?P<slug>[-\w]+)/update/',
        views.PostUpdateView.as_view(), name='post_update'
    ),
    re_path(r'(?P<slug>[-\w]+)/delete/',
        views.PostDeleteView.as_view(), name='post_delete'
    ),
    re_path(r'(?P<slug>[-\w]+)/comment/create/',
        views.CommentCreateView.as_view(), name='comment_create'
    ),
    re_path(r'(?P<slug>[-\w]+)/',
        views.PostDetailView.as_view(), name='post_detail'
    ),
]

social/blog/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse

from ckeditor.fields import RichTextField

from social.blog.managers import PostManager


class Post(models.Model):
    title = models.CharField(max_length=255)
    description = RichTextField(blank=True)
    slug = models.SlugField(max_length=255, unique=True, allow_unicode=True)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    likes = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='post_likes',
        blank=True
    )
    favorites = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='PostFavorite',
        related_name='post_favorites',
        blank=True
    )
    image = models.ImageField(upload_to='post/')
    active = models.BooleanField(default=True)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)

    objects = PostManager()

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
    
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title, allow_unicode=True)
        
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])

    @property
    def count_likes(self):
        return self.likes.count()
    

class PostFavorite(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE
    )
    post = models.ForeignKey(
        Post, 
        on_delete=models.CASCADE
    )
    datetime_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'post')
        verbose_name = 'Post Favorite'
        verbose_name_plural = 'Posts Favorites'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    body = models.TextField()
    likes = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='comment_likes',
        blank=True
    )
    reply = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        related_name='replies',
        blank=True,
        null=True
    )
    datetime_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'
    
    def __str__(self):
        return f'{self.author} - {self.post.title}'
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.post.slug])

    @property
    def count_likes(self):
        return self.likes.count()
    

social/blog/forms.py
from django import forms

from social.blog.models import Comment, Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'description', 'image',)


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

social/blog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import get_user_model
from django.contrib.postgres.search import SearchVector

from social.blog.models import Post, Comment
from social.notifications.models import Notification
from social.blog.forms import CommentCreateForm, PostCreateForm
from social.blog.mixins import PostOwnerMixin


User = get_user_model()


class PostListView(generic.ListView):
    queryset = Post.objects.active()
    context_object_name = 'posts'
    template_name = 'blog/post_list.html'
    paginate_by = 5


class PostDetailView(generic.DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        post = self.get_object()
        comments = post.comments.all()
        
        post_liked = True if user in post.likes.all() else False

        context['comment_form'] = CommentCreateForm()
        context['comments'] = comments
        context['post_liked'] = post_liked

        return context


class PostCreateView(
        PostOwnerMixin,
        LoginRequiredMixin,
        generic.CreateView
    ):
    form_class = PostCreateForm
    template_name = 'blog/post_create.html'


class PostUpdateView(
        UserPassesTestMixin,
        PostOwnerMixin,
        LoginRequiredMixin, 
        generic.UpdateView
    ):
    model = Post
    form_class = PostCreateForm
    template_name = 'blog/post_update.html'

    def test_func(self):
        obj = self.get_object()
        user = self.request.user
        
        if user == obj.owner or user.is_superuser:
            return True
        return False


class PostDeleteView(
        UserPassesTestMixin,
        LoginRequiredMixin, 
        generic.DeleteView
    ):
    model = Post
    template_name = 'blog/post_delete.html'

    def test_func(self):
        obj = self.get_object()
        user = self.request.user
        
        if user == obj.owner or user.is_superuser:
            return True
        return False
    

class UserPostListView(generic.ListView):
    template_name = 'blog/user_post_list.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        username = self.kwargs.get('username')
        user = get_object_or_404(User, username=username)
        return Post.objects.active().filter(owner=user)


class CommentCreateView(generic.CreateView):
    form_class = CommentCreateForm

    def form_valid(self, form):
        obj = form.save(commit=False)

        user = self.request.user
        post_slug = self.kwargs.get('slug')
        post = get_object_or_404(Post, slug=post_slug)
        comment_id = self.request.POST.get('comment_id')

        obj.author = user
        obj.post = post

        if comment_id:
            comment = get_object_or_404(Comment, pk=comment_id)
            obj.reply = comment

        obj.save()
        
        notify = Notification(
            sender=user,
            post=post,
            comment=obj, 
            text=obj.body, 
            type=3
        )
        notify.save()
        
        return super().form_valid(form)
    

class SearchListView(generic.ListView):
    template_name = 'blog/post_search_list.html'
    context_object_name = 'posts'

    def get_queryset(self) -> QuerySet[Any]:
        query = self.request.GET.get('q')
        return Post.objects.active()\
            .annotate(search=SearchVector('title', 'owner__username'))\
            .filter(search=query)
    

class WishListView(generic.ListView):
    template_name = 'blog/post_wish_list.html'
    context_object_name = 'posts'

    def get_queryset(self):
        user = self.request.user
        return Post.objects.active().filter(favorites=user)
    

class UserPostLikeView(generic.ListView):
    template_name = 'blog/post_user_like_list.html'
    context_object_name = 'posts'

    def get_queryset(self):
        user = self.request.user
        return user.post_likes.active()
    

def post_favorite(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    user = request.user

    if user in post.favorites.all():
        post.favorites.remove(user)
        notify = Notification.objects.filter(post=post, sender=user, type=5)
        notify.delete()        
    else:
        post.favorites.add(user)
        notify = Notification(post=post, sender=user, type=5)
        notify.save()

    return redirect(post.get_absolute_url())


def post_like(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    user = request.user

    if user in post.likes.all():
        post.likes.remove(user)
        notify = Notification.objects.filter(post=post, sender=user, type=1)
        notify.delete()
    else:
        post.likes.add(user)
        notify = Notification(post=post, sender=user, type=1)
        notify.save()

    return redirect(post.get_absolute_url())


def comment_like(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    user = request.user

    if user in comment.likes.all():
        comment.likes.remove(user)
        notify = Notification.objects.filter(comment=comment, sender=user, type=4)
        notify.delete()
    else:
        comment.likes.add(user)
        notify = Notification(comment=comment, sender=user, type=1)
        notify.save()

    return redirect(comment.get_absolute_url())

social/blog/templates/blog/comment_create.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block page_title %}
    Comment Create Page
{% endblock page_title %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Save">
    </form>
{% endblock content %}

social/blog/templates/blog/post_create.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block page_title %}
    Post Create Page
{% endblock page_title %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Save">
    </form>
{% endblock content %}

social/blog/templates/blog/post_delete.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block page_title %}
    Post Delete Page
{% endblock page_title %}

{% block content %}
    <h4>Are you sure you want to delete {{ post.title }}</h4>
    <input type="submit" value="Delete">
{% endblock content %}

social/blog/templates/blog/post_detail.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block page_title %}
    Post Detail Page
{% endblock page_title %}

{% block content %}
    <img src="{{ post.image.url }}" alt="">
    {% if user in post.favorites.all %}
        <form action="{% url 'blog:post_save' post.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="UnBookmark">
        </form>
    {% else %}
        <form action="{% url 'blog:post_save' post.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="Bookmark">
        </form>
    {% endif %}
    <p>{{ post.description|safe }}</p>
    <p>{{ post.author }}</p>
    <p>{{ post.count_likes }}</p>
    <p>{{ post_liked }}</p>
    {% if post_liked %}
        <form action="{% url 'blog:post_like' post.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="DisLike">
        </form>
    {% else %}
        <form action="{% url 'blog:post_like' post.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="Like">
        </form>
    {% endif %}
    <br><br>
    {% for comment in comments %}
        <p>{{ comment.body }}</p>
        <p>{{ comment.author }}</p>
        <form action="{% url 'blog:comment_create' post.slug %}" method="POST">
            {% csrf_token %}
            <input type="hidden" value="{{ comment.pk }}" name="comment_id">
            {{ comment_form|crispy }}
            <input type="submit" value="Save">
        </form>
        {% if user in comment.likes.all %}
            <form action="{% url 'blog:comment_like' comment.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="DisLike">
            </form>
        {% else %}
            <form action="{% url 'blog:comment_like' comment.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="Like">
            </form>
        {% endif %}
        <p>{{ comment.count_likes }}</p>
        <hr>
    {% endfor %}
    <br><br>
    <form action="{% url 'blog:comment_create' post.slug %}" method="POST">
        {% csrf_token %}
        {{ comment_form|crispy }}
        <input type="submit" value="Save">
    </form>
{% endblock content %}

social/blog/templates/blog/post_list.html
{% extends '_base.html' %}

{% block page_title %}
    Post List Page
{% endblock page_title %}

{% block content %}
    {% for post in posts %}
        <img src="{{ post.image.url }}" alt="">
        <a href="{{ post.get_absolute_url }}"><h4>{{ post.title|truncatewords:15 }}</h4></a>
        <p>{{ post.description|safe }}</p>
        <p>{{ post.author }}</p>
        <p>{{ post.count_likes }}</p>
        <br>
    {% endfor %}
{% endblock content %}

social/blog/templates/blog/post_search_list.html
{% extends '_base.html' %}

{% block page_title %}
    Post Search List Page
{% endblock page_title %}

{% block content %}
    {% for post in posts %}
        <img src="{{ post.image.url }}" alt="">
        <a href="{{ post.get_absolute_url }}"><h4>{{ post.title|truncatewords:15 }}</h4></a>
        <p>{{ post.description|safe }}</p>
        <p>{{ post.author }}</p>
        <p>{{ post.count_likes }}</p>
        <br>
    {% endfor %}
{% endblock content %}

social/blog/templates/blog/post_update.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block page_title %}
    Post Update Page
{% endblock page_title %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Update">
    </form>
{% endblock content %}

social/blog/templates/blog/post_user_like_list.html
{% extends '_base.html' %}

{% block page_title %}
    Post User Like List Page
{% endblock page_title %}

{% block content %}
    {% for post in posts %}
        <img src="{{ post.image.url }}" alt="">
        <a href="{{ post.get_absolute_url }}"><h4>{{ post.title|truncatewords:15 }}</h4></a>
        <p>{{ post.description|safe }}</p>
        <p>{{ post.author }}</p>
        <p>{{ post.count_likes }}</p>
        <br>
    {% endfor %}
{% endblock content %}

social/blog/templates/blog/post_wish_list.html
{% extends '_base.html' %}

{% block page_title %}
    Post Wish List Page
{% endblock page_title %}

{% block content %}
    {% for post in posts %}
        <img src="{{ post.image.url }}" alt="">
        <a href="{{ post.get_absolute_url }}"><h4>{{ post.title|truncatewords:15 }}</h4></a>
        <p>{{ post.description|safe }}</p>
        <p>{{ post.author }}</p>
        <p>{{ post.count_likes }}</p>
        <br>
    {% endfor %}
{% endblock content %}

social/blog/templates/blog/user_post_list.html
{% extends '_base.html' %}

{% block page_title %}
    User Post List Page
{% endblock page_title %}

{% block content %}
    {% for post in posts %}
        <img src="{{ post.image.url }}" alt="">
        <a href="{{ post.get_absolute_url }}"><h4>{{ post.title|truncatewords:15 }}</h4></a>
        <p>{{ post.description|safe }}</p>
        <p>{{ post.author }}</p>
        <br>
    {% endfor %}
{% endblock content %}