config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('social.accounts.urls', namespace='accounts')),
    path('', include('social.pages.urls', namespace='pages')),
    path('blog/', include('social.blog.urls', namespace='blog')),
    path('notifications/', include('social.notifications.urls', namespace='notifications')),
    path('chat/', include('social.chat.urls', namespace='chat')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('users/', views.ProfileListView.as_view(), name='user_list'),
    path('users/<str:username>/', views.ProfileDetailView.as_view(), name='user_detail'),
    path('follow/', views.follow_view, name='follow'),
]

social/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

from PIL import Image


class CustomUser(AbstractUser):
    pass


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    following = models.ManyToManyField(
        'self',
        related_name='followers',
        symmetrical=False,
        blank=True
    )
    bio = models.CharField(max_length=255, blank=True)
    image = models.ImageField(upload_to='profile/', default='default-avatar.jpg')
    birth_date = models.DateField(blank=True, null=True)
    is_online = models.BooleanField(default=False)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        image = Image.open(self.image.path)
        if image.height > 300 or image.width > 300:
            output_size_image = (300, 300)
            image.thumbnail(output_size_image)
            image.save(self.image.path)

    @property
    def count_following(self):
        return self.following.count()
    
    @property
    def count_followers(self):
        return self.followers.count()

social/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

from social.accounts.models import Profile


User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email',)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email',)


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username',)


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'image', 'birth_date',)

social/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic, View
from django.contrib.auth.mixins import LoginRequiredMixin

from social.accounts.forms import \
    UserUpdateForm, \
    ProfileUpdateForm
from social.accounts.models import Profile
from social.notifications.models import Notification


class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

        return render(request, 'accounts/profile.html', {
            'user_form': user_form,
            'profile_form': profile_form,
        })

    def post(self, request):
        user_form = UserUpdateForm(
            request.POST, instance=request.user
        )
        profile_form = ProfileUpdateForm(
            request.POST, instance=request.user.profile
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('accounts:profile')


class ProfileListView(generic.ListView):
    template_name = 'accounts/profile_list.html'
    context_object_name = 'profiles'

    def get_queryset(self):
        return Profile.objects.exclude(user=self.request.user)


class ProfileDetailView(generic.DetailView):
    model = Profile
    template_name = 'accounts/profile_detail.html'
    context_object_name = 'profile'

    def get_object(self):
        username = self.kwargs.get('username')
        profile = get_object_or_404(Profile, user__username=username)
        return profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = self.request.user
        profile = self.get_object()

        if user.profile in profile.followers.all():
            follow = True
        else:
            follow = False

        context['follow'] = follow
        return context


def follow_view(request):
    if request.method == 'POST':
        my_profile = get_object_or_404(Profile, user=request.user)
        obj_pk = request.POST.get('profile_pk')
        obj = get_object_or_404(Profile, pk=obj_pk)
        user = request.user

        if obj in my_profile.following.all():
            my_profile.following.remove(obj.user.profile)
            notify = Notification.objects.filter(sender=user, notification_type=2)
            notify.delete()
        else:
            my_profile.following.add(obj.user.profile)
            notify = Notification(sender=user, user=obj.user, notification_type=2)
            notify.save()

        return redirect(request.META.get('HTTP_REFERER'))

    return redirect('accounts:users_list')

social/accounts/templates/accounts/profile.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block page_title %}
    Profile
{% endblock page_title %}

{% block content %}
    <img src="{{ user.profile.image.url }}" alt="img">
    <h4>{{ user.first_name }} {{ user.last_name }} {{ user.username }}</h4>
    <p>followers---{{ user.profile.count_followers }}---</p>
    <br>
    <p>following---{{ user.profile.count_following }}---</p>
    <br>
    <form action="" method="POST">
        {% csrf_token %}
        {{ user_form|crispy }}
        {{ profile_form|crispy }}
        <input type="submit" class="btn btn-success" value="Save">
    </form>
{% endblock content %}

social/accounts/templates/accounts/profile_detail.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block page_title %}
    Profile Detail
{% endblock page_title %}

{% block content %}
    <h4>{{ profile.user }}</h4>
    <p>following: {{ profile.count_following }}</p>
    <p>follower: {{ profile.count_followers }}</p>
    <p>{{ profile.is_online }}</p>
    <img src="{{ profile.image.url }}" alt="">
    <p>
        {% if follow %}
            <form action="{% url 'accounts:follow' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="profile_pk" value="{{ profile.pk }}">
                <input type="submit" value="UnFollow">
            </form>
        {% else %}
            <form action="{% url 'accounts:follow' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="profile_pk" value="{{ profile.pk }}">
                <input type="submit" value="Follow">
            </form>
        {% endif %}
    </p>
{% endblock content %}

social/accounts/templates/accounts/profile_list.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block page_title %}
    All Profile
{% endblock page_title %}

{% block content %}
    {% for profile in profiles %}
        <a href="{% url 'accounts:user_detail' profile.user %}">
            <h4>{{ profile.user }}</h4>
        </a>
        <br>
    {% endfor %}
{% endblock content %}